src/Main.hs

fixes https://github.com/jaspervdj/stylish-haskell/issues/112

Add `--version` option

---

README.markdown

https://www.archlinux.org/packages/community/x86_64/stylish-haskell/

add arch linux to package managers

---

lib/Language/Haskell/Stylish/Align.hs

Add a guard for maximum error case

---

lib/Language/Haskell/Stylish/Parse.hs
tests/Language/Haskell/Stylish/Parse/Tests.hs

Remove MagicHash from whitelisted extensions

---

CHANGELOG
lib/Language/Haskell/Stylish/Step/Imports.hs
tests/Language/Haskell/Stylish/Step/Imports/Tests.hs

Say if I should add more comments or change something.
(I decided not to make it configurable because after some thinking I couldn't find a reason to do it.)

Deduplicate import specs

---

lib/Language/Haskell/Stylish/Config.hs
src/Main.hs
stylish-haskell.cabal

Use file-embed for default configuration

---

README.markdown
scripts/latest.sh
scripts/stylish-haskell.sh

Closes https://github.com/jaspervdj/stylish-haskell/issues/194.
Haven't tested (paths set for when merged) but think this should do the trick!

Add scripts to run with pipe recipe.

---

stylish-haskell.cabal

Builds fine and all tests pass.

Allow yaml 0.9

---

scripts/latest.sh

Currently doesn't work. get following error.
```sh
$ curl -sL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s .
Downloading and running stylish-haskell...
######################################################################## 100.0%
sh: 21: .stylish-haskell-98MYQ/stylish-haskell-https://github.com//jaspervdj/stylish-haskell/releases/download/v0.9.2.0/stylish-haskell-v0.9.2.0-linux-x86_64.tar.gz/stylish-haskell: not found
```

Fix script

---

LICENSE
doc/stylish-haskell.1.adoc

Add Debian's manpage for stylish-haskell to this repo

---

stylish-haskell.cabal

Builds fine and all tests pass here.

Allow strict 0.4

---

tests/Language/Haskell/Stylish/Step/Imports/Tests.hs

Hi @jaspervdj,
I noticed your last changes from #307 fix #184 issue. I add a test case to cover this.

Adds a test to cover remove duplicates imports case

---

default.nix
haskell-pkgs.nix
shell.nix

Open the `nix-shell` in the root directory and run `cabal new-test` to see that it's working

Add nix shell

---

lib/Language/Haskell/Stylish/Printer.hs
lib/Language/Haskell/Stylish/Step/Data.hs
lib/Language/Haskell/Stylish/Step/ModuleHeader.hs
tests/Language/Haskell/Stylish/Step/Data/Tests.hs

Fix some issues with record padding

---

lib/Language/Haskell/Stylish/Step/SimpleAlign.hs
tests/Language/Haskell/Stylish/Step/SimpleAlign/Tests.hs

Add support for aligning multi way ifs

---

lib/Language/Haskell/Stylish/Printer.hs
tests/Language/Haskell/Stylish/Step/Data/Tests.hs

Addressing ticks dropping from records that contain promoted data types.

Better support for datakinds in records

---

README.markdown

Add HLS as a way for editor integration (#347)

---

README.markdown

Correct badge URL

---

data/stylish-haskell.yaml
lib/Language/Haskell/Stylish/Config.hs
lib/Language/Haskell/Stylish/Step/LanguagePragmas.hs
tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs

Closes #278. See details in that issue.

Add a language pragma style "vertical_compact".

---

.github/workflows/ci.yml
default.nix
haskell-pkgs.nix
shell.nix

Few nix improvements to make our life easier

Nix improvements

---

stylish-haskell.cabal
tests/Language/Haskell/Stylish/Regressions.hs
tests/Language/Haskell/Stylish/Step/Data/Tests.hs
tests/TestSuite.hs

Closes #198
Closes #273
Closes #282

Closing few issues

---

lib/Language/Haskell/Stylish/Parse.hs
tests/Language/Haskell/Stylish/Parse/Tests.hs

Fix parsing of NoXyz extensions

---

scripts/latest.sh

support a new style of the GitHub releases page

---

stylish-haskell.cabal

See: 
- https://github.com/commercialhaskell/stackage/issues/7031
Published as revision 1 of 0.14.5.0.

Allow aeson-2.2

---

tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs

See https://gitlab.haskell.org/ghc/ghc/-/issues/23984

Add test case using empty line
