README.markdown
Apparently the wiki fails to redirect properly, resulting in an error page from mediawiki.
=> Fix the link to Emacs/Formatting on the HaskellWiki

CHANGELOG, README.markdown
Move the entry for 0.5.9.0 to where it should be.  Thanks.
=> Move CHANGELOG entry for 0.5.9.0 from README

README.markdown
This package is now available from the Debian and Ubuntu package repositories.
=> Debian and Ubuntu installation instructions

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, src/Main.hs
`writeFile` from Haskell uses native newline format, so on Windows all files end with CRLF after running `stylish-haskell`. This PR allows setting line endings (LF or CRLF) optionally. Default value (`native`) gives previous behavior.
=> Add newline format option

lib/Language/Haskell/Stylish/Parse.hs, tests/Language/Haskell/Stylish/Parse/Tests.hs
See the comments for a detailed explanation.
Fixes jaspervdj/stylish-haskell#117
=> Add a set of default language extensions for parsing

README.markdown
atom-beautify also supports Haskell via stylish-haskell, hence a reference here would probably be good.
=> Added reference to atom-beautify

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
So I can get something like:
```hs
import           Prelude ()
import           Prelude.Compat hiding
(foldMap)
import           Data.List
(foldl', intercalate)
```
I'd like to make a follow-up so, padding could be specified as `module_name` so it could be *7* or *17*, depending whether there is a qualified import
=> Empty list align

README.markdown
I tried this one and it works just fine. It is a better way to use it in Vim.
=> Add Vim usage method in README

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
The tests show the functionality:
makes it possible not to hardcode `list_padding` to constant value, which is handy with `file` and `group` `align` - variants:
```hs
module Foo where
import Prelude ()
import Prelude.Compat hiding
(foldMap)
import Data.List
(foldl', intercalate)
```
=> list_padding: module_name

lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
Fixes #70 and #90. This only keeps the annotations but doesn't do any alignment or padding. IMHO still fine since they're so rarely used.
=> Keep `safe` and `{-# SOURCE #-}` import annotations

CHANGELOG, lib/Language/Haskell/Stylish/Step/LanguagePragmas.hs, tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs
See #154 for an example:
```
{-# LANGUAGE DefaultSignatures, FlexibleInstances, LambdaCase, TypeApplications
#-}
```
This PR prevents the situation above by glueing `#-}` to the last pragma. In the case above, it leads to the following rendering:
```
{-# LANGUAGE DefaultSignatures, FlexibleInstances, LambdaCase,
TypeApplications #-}
```
The PR doesn't affect cases when the whole line fits into the character limit.
=> Don't leave #-} hanging

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
eg:
import Data.Foo ( foo )
instead of 
import Data.Foo (foo)
=> Space surround

README.markdown
This PR just modifies the styling of the README examples to be syntax-highlighted.
=> Add syntax highlighting to README examples

lib/Language/Haskell/Stylish/Parse.hs, tests/Language/Haskell/Stylish/Parse/Tests.hs
`nix-shell` has the ability to be used as an interpreter since [version 1.9](https://nixos.org/releases/nix/nix-1.9/manual/#ssec-relnotes-1.9), and the release notes provide an example using Haskell. GHC supports this without any issues, but stylish-haskell only strips the first shebang line and then fails because it cannot parse the file. This provides the ability to strip up to the first two shebang lines.
=> Remove shebang lines

scripts/latest.sh
So, it doesn't work yet ;) 
This fix makes the pattern grab the release names you give (`linux` comes before `x86_64`).
Tested with:
```
$ RELEASES=$(curl --silent https://github.com/jaspervdj/stylish-haskell/releases)
$ URL=https://github.com/$(echo $RELEASES | grep -o '\"[^\"]*-linux-x86_64\.tar\.gz\"' | sed s/\"//g | head -n1)
$ echo $URL
```
=> Fix pattern to match release names.

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Align.hs, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Squash.hs, lib/Language/Haskell/Stylish/Util.hs, stylish-haskell.cabal, tests/Language/Haskell/Stylish/Step/Squash/Tests.hs, tests/TestSuite.hs
This step basically undoes the effect of `simple_align`. For instance, a case expression like
```
case <expr> of
Nothing        -> <expr>
Just something -> <expr>
```
gets squashed to
```
case <expr> of
Nothing -> <expr>
Just something -> <expr>
```
Similarly, multiple spaces in record definitions and top level matches get squashed.
It is enabled via
```
- steps:
[...]
- squash: {}
[...]
```
in `.stylish-haskell.yaml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jaspervdj/stylish-haskell/207)
=> Add new step to squash multiple spaces between some elements

lib/Language/Haskell/Stylish/Config.hs, stack.yaml, stylish-haskell.cabal
Bumped up the lower bound from `yaml` in order to avoid using `decodeEither`, which is now deprecated. `yaml-0.8.11` was released in [April 2015](https://github.com/snoyberg/yaml/releases/tag/yaml%2F0.8.11), so I don't see why anyone would have a problem upgrading that.
=> Update bounds to support lts-13.0

README.markdown
A more generic and better-behaving plugin than `vim-stylish-haskell`, so worth mentioning as an alternative
=> README: Mention vim-autoformat

stack.yaml, stylish-haskell.cabal
When using `1.21.0`, this allows for correct parsing of `DerivingVia` syntax.
Keep in mind that it's up to the person building `stylish-haskell` to ensure that the most up-to-date version of `haskell-src-exts` is being used :)
=> Bump `haskell-src-exts` upper bound

lib/Language/Haskell/Stylish/Step/TrailingWhitespace.hs, tests/Language/Haskell/Stylish/Step/TrailingWhitespace/Tests.hs
Page breaks are an old but effective way of bookmarking a file. They
usually are single character lines. Stylish removes them as whitespace
characters, and they are from the compiler's point of view but not
from an editor's perspective.
Resolves #208
=> Repsect page breaks alone in a line

stack.yaml
In this new snapshot we have among other things a more recent version of `haskell-src-exts` which fixes a few of the parsing issues `stylish-haskell` has.
It definitely solves #210 but might also solve other issues like the ones to do with DerivingVia parsing.
=> Update to Stack LTS 14.4

stylish-haskell.cabal
optparse-applicative has upgraded to GHC 8.8.1 in the 0.15 version.
=> Add support for GHC 8.8.1

stack.yaml, stack.yaml.lock, stylish-haskell.cabal
haskell-src-exts-1.23.0 adds support for BlockArguments :)
=> Bump haskell-src-exts to 1.23

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish.hs, lib/Language/Haskell/Stylish/Align.hs, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, lib/Language/Haskell/Stylish/Step/LanguagePragmas.hs, lib/Language/Haskell/Stylish/Step/SimpleAlign.hs, lib/Language/Haskell/Stylish/Util.hs, tests/Language/Haskell/Stylish/Config/Tests.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs, tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs, tests/Language/Haskell/Stylish/Step/SimpleAlign/Tests.hs
In some projects I permit arbitrarily long lines, and so I do not want the `columns` setting.
This PR changes the type of the `configColumns` field from `Int` to `Maybe Int`, and allows you to write `columns: null` in `.stylish-haskell.yaml` to disable all line wrapping features.
In addition to the modification to the `Config` type, there are also many functions with an argument type that changes from `Int` to `Maybe Int`, so this would be a significant breaking change to the library.
A workaround without this change would be to simply set some very large number, e.g. `columns: 9223372036854775807`, but that seems rather inelegant.
I did not fully understand what I was doing in the `Util` module, so that part in particular may be worth reviewing.
=> Allow setting "columns: null" to disable all wrapping

README.markdown, data/stylish-haskell.yaml, lib/Language/Haskell/Stylish.hs, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Data.hs, stylish-haskell.cabal, tests/Language/Haskell/Stylish/Config/Tests.hs, tests/Language/Haskell/Stylish/Step/Data/Tests.hs, tests/TestSuite.hs
(Optionally) turns this:
```
module Herp where
data Foo a = Foo { a :: Int, a2 :: String } | Bar { b :: a } 
```
into
```
module Herp where
data Foo a = Foo 
{ a :: Int
, a2 :: String 
} 
| Bar
{ b :: a
}
```
=> Support for records formatting

lib/Language/Haskell/Stylish/Step/Data.hs, tests/Language/Haskell/Stylish/Step/Data/Tests.hs
After this change records with comments will be formatted and comments will *not* get deleted
=> Fix records with comments

lib/Language/Haskell/Stylish.hs, stylish-haskell.cabal, testdata/test-config.yaml, tests/Language/Haskell/StylishSpec.hs, tests/TestSuite.hs
It's going to be needed for the haskell-ide integration
=> Expose "format" function in Sylish.hs

stylish-haskell.cabal, testdata/test-config.yaml, tests/Language/Haskell/Stylish/Config/Tests.hs, tests/Language/Haskell/Stylish/Tests.hs, tests/Language/Haskell/Stylish/Tests/Util.hs, tests/Language/Haskell/StylishSpec.hs, tests/TestSuite.hs
Minor test tweaks:
-  Move `withTestDirTree` to the util module so it can be reused
-  Use the `withTestDirTree` function in the `Stylish` tests
-  Rename the `StylishSpec` file to the `.Tests` scheme
=> Tweak tests

lib/Language/Haskell/Stylish/Step/Data.hs, tests/Language/Haskell/Stylish/Step/Data/Tests.hs, tests/Language/Haskell/Stylish/Tests.hs
Perhaps the safest way for now is to revert to old behavior for data
types -- i.e. do nothing. Attemmpt reformatting only if at least one
constructor has record fields.
Fixes https://github.com/jaspervdj/stylish-haskell/issues/262
=> Disable formatting of data types without records

lib/Language/Haskell/Stylish.hs, src/Main.hs, tests/Language/Haskell/Stylish/Tests.hs
This could be one solution to #162 .
There is an added *-r* command-line switch that accepts a folder as its input to search for Haskell source files recursively. In a CI script the already suggested solution in #162 is feasible, however in case _stylish-haskell_ can solve it itself the CI script would become easier.
There are pending questions:
- whether you are happy with logging, that is only available in when verbose mode is enabled.
- Could we combine this implementation right away together with #200 ?
- Should the application default to Haskell file extension(s) by default implicitly or should be there another optional argument to specify file extension(s)?
=> Recursing directories to find Haskell source files.

stylish-haskell.cabal
The bounds of Cabal were not updated in 2dd6fbd669e3501d5d4783dfa2d9f9ba3026ea1b
All tests pass here with the new Cabal.
=> Allow Cabal 3.2 for test suite

stack.yaml, stack.yaml.lock
This PR reduces the final binary size of `stylish-haskell` on my machine from 19mb to 7.9mb. Experimentally, using `-split-sections` like this doesn't introduce a compilation time penalty, although it does require that dependencies be rebuilt (hopefully once and then cached, as with CI).
I also bumped the Stackage LTS, and removed pins that were no longer necessary.
=> Use `-split-sections`

stack.yaml
The use of `split-sections` in stack.yaml breaks the build on macOS. Fixes https://github.com/jaspervdj/stylish-haskell/issues/304.
=> Remove split-sections stanza

stylish-haskell.cabal
They are not needed on newer GHC.
=> Depend on semigroups only on GHC < 8.0

lib/Language/Haskell/Stylish/Module.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
When some import line spans multuple lines, e.g. when import list is
long, stylish-haskell breaks a group at this line, leading to bad
result.
This commits makes sure that import groups are recognized solely by
empty lines.
---
I hope it's straightforward from the test case :)
Thanks for this awesome tool. Most likely I will make a couple more PRs in the next few days.
=> Fix "group" import sort with multi-line imports

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Data.hs, tests/Language/Haskell/Stylish/Step/Data/Tests.hs
Not everyone wants their typeclasses sorted.
=> Make sorting deriving list optional

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/ModuleHeader.hs, tests/Language/Haskell/Stylish/Step/ModuleHeader/Tests.hs
Alternatively, make it the default behavior? I don't think I've ever seen someone add a new line before `where` like that before.
=> Add `break_only_where` option

lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/ModuleHeader/Tests.hs
This is necessary to export pattern synonyms bundled with a type. I went with moving the ellipsis to the beginning of the `IEThingWith` list, to match the style from the GHC User's guide, though this could become a setting if there's interest for e.g. moving it to the end.
See https://downloads.haskell.org/ghc/latest/docs/html/users_guide/glasgow_exts.html#import-and-export-of-pattern-synonyms
=> Keep wildcard if present in IEThingWith

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Printer.hs, lib/Language/Haskell/Stylish/Step/ModuleHeader.hs, tests/Language/Haskell/Stylish/Step/ModuleHeader/Tests.hs
Previously, the `break_only_where` option of `module_header` allowed choosing
between the following two styles:
1. `break_only_where: false`:
```haskell
module Foo where
module Bar
( main
) where
```
2. `break_only_where: true`:
```haskell
module Foo
where
module Bar
( main
) where
```
In case a module only has a single export (e.g., `main` or `tests`) or no
exports at all (e.g., a module defining orphans), we still "break" the `where`:
```haskell
module Bar
( main
) where
module Orphans
(
) where
```
It should be possible to print these module headers as:
```haskell
module Bar (main) where
module Orphans () where
```
We generalise the `break_only_where` option to `break_where` with the following
three possible values:
- `exports`: only break when there is an explicit export list.
- …
=> Generalise break_only_where to allow single-line module headers

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/ModuleHeader.hs, tests/Language/Haskell/Stylish/Step/ModuleHeader/Tests.hs
Previously the formatter of module header would always add open
bracket of the export list on the next line after the module name.
With this change we give user ability to customize this behavior. The
open bracket ends up either on the same line as module name or on the
next line.
For backward compatibility we keep the 'next_line' a default behavior.
=> Add new configuration to ModuleHeader step

tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs
Fixes: 
```
~/stylish-haskell/tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs:232:1: error:
Duplicate type signatures for ‘case13’
at tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs:221:1-6
tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs:232:1-6
|       
232 | case13 :: Assertion
| ^^^^^^
~/stylish-haskell/tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs:233:1: error:
Multiple declarations of ‘case13’
Declared at: tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs:222:1
tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs:233:1
|       
233 | case13 = expected @=? testStep (step Nothing VerticalCompact False False "language") input
| ^^^^^^
```
=> Fixes compile error introduced in previous commit

.github/workflows/ci.yml
Should we continue maintaining the Mac OS in CI? It's the second time I'm bumping it this week
=> Bump CI Mac Cache

.github/workflows/ci.yml, README.markdown, scripts/latest.sh, scripts/stylish-haskell.sh, stylish-haskell.cabal, tests/Language/Haskell/Stylish/Step/Data/Tests.hs, tests/Language/Haskell/Stylish/Step/Imports/FelixTests.hs
This small PR updates all links to the old repo to this one, mostly so that the scripts can work again.
I left the link to the build icon untouched, just to be safe, but I can include it if required.
The code change is only the result of running stylish-haskell on the file when saving it. :)
=> Update references to old repo.

.github/workflows/ci.yml, lib/Language/Haskell/Stylish/Step/Data.hs, tests/Language/Haskell/Stylish/Step/Data/Tests.hs
- also don't remove context from data declarations
Fixes: https://github.com/haskell/stylish-haskell/issues/339
=> Don't remove existential quantification (#339)

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
Based on the work started by @jhmcstanton. I added a few more test cases, and adapted the logic to support them. I originally submitted this as a PR to @jhmcstanton's branch, but I haven't got a reply, so I thought submitting a PR including their commit might be simpler.
Adds an option to use post qualified module imports.
Related to #284
Resolves #334
Improves on #335 
Let me know if any more tests or changes are needed.
=> Add support for post qualified import formatting (more cases)

lib/Language/Haskell/Stylish/GHC.hs, lib/Language/Haskell/Stylish/Module.hs, lib/Language/Haskell/Stylish/Ordering.hs, lib/Language/Haskell/Stylish/Step/Data.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
Fixes #6 (again), includes #383.
=> Case insensitive import sort

stylish-haskell.cabal
Hello, this pr adds a ghc-lib flag to force use ghc-lib-parser even if ghc is supported. HLS will benefit a lot since we can support hls-stylish-haskell-plugin and hls-hlint-plugin on ghc9.2 simultaneously.  I would appreciate it if this pr is accepted with a new release. Thanks in advance.
The necessity is here https://github.com/haskell/haskell-language-server/pull/2854#discussion_r858874680
=> Add ghc-lib flag to force use ghc-lib-parser even if ghc is supported

data/stylish-haskell.yaml, lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, stylish-haskell.cabal, tests/Language/Haskell/Stylish/Step/Imports/Tests.hs
This PR adds an option called `group_imports` (default: `false`) that automatically organizes imports into groups based on the first part of the module name:
``` haskell
import Data.List
import Control.Monad
import GHC.Exts
import Control.Applicative
import Data.Map
```
⇒
``` haskell
import Control.Applicative
import Control.Monad
import Data.List
import Data.Map
import GHC.Exts
```
I currently do this manually because I find that breaking up imports makes them much easier to scan. Now that I've started using haskell-language-server to insert most of my imports, it would be great if stylish-haskell could handle the grouping for me.
This is my first stab at the code to do this—not sure if there's a better approach.
Another option would be to let the user configure which order groups go in. …
=> Option to group imports automatically

stack.yaml
The resolver version is bumped to nightly-2022-06-06 which is the latest with ghc 9.2.2
This is done so that ghc-lib-parser* dependencies do not need to be defined as extra-deps
=> Bump resolver

lib/Language/Haskell/Stylish/Step/Data.hs, tests/Language/Haskell/Stylish/Step/Data/Tests.hs
Fixes #411
I've changed printer's behavior for alignment of deriving closes: now it adds newline and indentation before `deriving` even if `onelineEnum` is enabled:
```hs
data Foo = A | B | C
deriving (Eq, Show)
```
instead of
```hs
data Foo = A | B | C deriving (Eq, Show)
```
This behavior is what is said in docs:
> Deriving clauses are always on separate lines
Surely we can add an option to preserve the previous behavior, but I don't think that it's desired for several reasons:
- it conflicts with docs
- it leads to an awful output when enum is large, that even not highlight well:
```hs
data DefType = DefTEnv | DefTPref | DefTCmd | DefTInl | DefTMode | DefTSort deriving
( Eq
, Ord
, Show
)
```
However, if you think otherwise, I can add an option. Maybe while `break_enums` option was …
=> Deriving alignment for enums

lib/Language/Haskell/Stylish/Config.hs, lib/Language/Haskell/Stylish/Config/Cabal.hs, tests/Language/Haskell/Stylish/Config/Tests.hs
This is just like #412, but for .cabal files. This is what actually caused #414, so I hope it will be closed by the PR.
Also I've improved a bit tests for config parsing. I think they are not optimal, but now they are a bit better, than they were.
For the future plans I think it would be nice to some algebraic type for dealing with extensions. The current solution "via show" seems ugly and error-prone.
=> Fixed NoXyz issue for .cabal files

stylish-haskell.cabal
See https://github.com/haskell/stylish-haskell/issues/441#issuecomment-1409149858
Closes #441 (one would still have to make revisions for this to apply to already-published versions of course).
=> Flip `ghc-lib` flag default to `True`

.github/workflows/cabal.yml, README.markdown
separate from the current Stack GitHub Action
Build with GHC 9.2 looks good, maybe https://github.com/haskell/stylish-haskell/issues/405 can be closed
The build with GHC 9.4 fails: https://github.com/haskell/stylish-haskell/issues/449
=> Cabal GitHub action for GHC 9.0, 9.2, 9.4

.github/workflows/cabal.yml, cabal.project, lib/Language/Haskell/Stylish/GHC.hs, lib/Language/Haskell/Stylish/Module.hs, lib/Language/Haskell/Stylish/Ordering.hs, lib/Language/Haskell/Stylish/Parse.hs, lib/Language/Haskell/Stylish/Printer.hs, lib/Language/Haskell/Stylish/Step/Data.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, lib/Language/Haskell/Stylish/Step/ModuleHeader.hs, lib/Language/Haskell/Stylish/Step/SimpleAlign.hs, lib/Language/Haskell/Stylish/Step/Squash.hs, lib/Language/Haskell/Stylish/Step/UnicodeSyntax.hs, stack.yaml, stack.yaml.lock, stylish-haskell.cabal
=> Update to support GHC 9.6

lib/Language/Haskell/Stylish/Step/ModuleHeader.hs, tests/Language/Haskell/Stylish/Step/ModuleHeader/Tests.hs
=> Disapearing of `DEPRECATED` pragma attached to module fixed

.github/workflows/cabal.yml, lib/Language/Haskell/Stylish/Printer.hs, lib/Language/Haskell/Stylish/Step/Data.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, stack.yaml, stylish-haskell.cabal, tests/Language/Haskell/Stylish/Step/LanguagePragmas/Tests.hs
Work-in-progress. I did the obvious changes. There are a few test failures in the language pragma tests and I don't know why, otherwise it seems to work.
=> 9.8 support

.github/workflows/ci.yml, lib/Language/Haskell/Stylish/Config/Cabal.hs, src/Main.hs, stylish-haskell.cabal
@jaspervdj : the bump to Cabal-3.14 creates an issue downstream with haskell-language-server, where many ghc-9.10 plugins are hard limited to Cabal-3.12. This patch attempts to adress the situation.
@jhrcek : I think this respects the logic behind your changes.
=> Re-enabling Cabal-3.12

.github/workflows/ci.yml, lib/Language/Haskell/Stylish/Comments.hs, lib/Language/Haskell/Stylish/Config/Cabal.hs, lib/Language/Haskell/Stylish/GHC.hs, lib/Language/Haskell/Stylish/Module.hs, lib/Language/Haskell/Stylish/Printer.hs, lib/Language/Haskell/Stylish/Step/Data.hs, lib/Language/Haskell/Stylish/Step/Imports.hs, lib/Language/Haskell/Stylish/Step/LanguagePragmas.hs, lib/Language/Haskell/Stylish/Step/ModuleHeader.hs, lib/Language/Haskell/Stylish/Step/SimpleAlign.hs, lib/Language/Haskell/Stylish/Step/Squash.hs, lib/Language/Haskell/Stylish/Step/UnicodeSyntax.hs, stylish-haskell.cabal
Building on #480, this makes stylish-haskell functionally complete for ghc-9.12. Only one failing test left.
=> Upgrade to ghc 9.12
